# Generates OUTPUT_FILE, a C++ header embedding every *.glsl file of SHADERS_DIR
# as a string constant keyed by its file name. The GLSL sources therefore live
# inside the binary: no file to deploy next to the executable, no runtime path.
#
# Usage: cmake -DSHADERS_DIR=<dir> -DOUTPUT_FILE=<file> -P ArenaiEmbedShaders.cmake

if(NOT SHADERS_DIR OR NOT OUTPUT_FILE)
    message(FATAL_ERROR "SHADERS_DIR and OUTPUT_FILE are required")
endif()

file(GLOB shader_files "${SHADERS_DIR}/*.glsl")
list(SORT shader_files)

if(NOT shader_files)
    message(FATAL_ERROR "no *.glsl file found in ${SHADERS_DIR}")
endif()

set(entries "")
foreach(shader_file IN LISTS shader_files)
    get_filename_component(shader_name "${shader_file}" NAME)
    file(READ "${shader_file}" shader_source)
    # Raw string literal with a custom delimiter so the GLSL needs no escaping.
    # No newline is inserted after '(' : "#version" must stay on the first line.
    string(APPEND entries "        {\"${shader_name}\",\n         R\"__arenai_glsl__(${shader_source})__arenai_glsl__\"},\n")
endforeach()

string(CONCAT header_content
    "// Auto-generated by cmake/ArenaiEmbedShaders.cmake from arenai_view/shaders/*.glsl\n"
    "// Do not edit.\n"
    "\n"
    "#ifndef ARENAI_SHADERS_EMBEDDED_H\n"
    "#define ARENAI_SHADERS_EMBEDDED_H\n"
    "\n"
    "#include <string_view>\n"
    "#include <unordered_map>\n"
    "\n"
    "namespace arenai::view {\n"
    "\n"
    "    inline const std::unordered_map<std::string_view, std::string_view> EMBEDDED_SHADERS = {\n"
    "${entries}"
    "    };\n"
    "\n"
    "}// namespace arenai::view\n"
    "\n"
    "#endif// ARENAI_SHADERS_EMBEDDED_H\n"
)

file(WRITE "${OUTPUT_FILE}" "${header_content}")
