# Compiles the Vulkan GLSL shaders to SPIR-V at build time and embeds the
# resulting binaries into a generated C++ header (EMBEDDED_SPIRV map keyed by
# the .glsl file name). The executables need no shader file at runtime, and
# shader errors break the build instead of the first frame.
#
# Two modes, like ArenaiEmbedShaders.cmake before it:
#  - included from a CMakeLists: provides
#    arenai_compile_shaders(<shaders_dir> <gen_dir> <out_header> <sources_var>)
#  - script mode: cmake -DSPV_DIR=<dir> -DOUTPUT_FILE=<file>
#                       -P ArenaiCompileShaders.cmake
#    packs every *.spv of SPV_DIR into the header.

##### script mode: .spv files -> C++ header #####
if (CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    if (NOT SPV_DIR OR NOT OUTPUT_FILE)
        message(FATAL_ERROR "SPV_DIR and OUTPUT_FILE are required")
    endif ()

    file(GLOB spv_files "${SPV_DIR}/*.spv")
    list(SORT spv_files)
    if (NOT spv_files)
        message(FATAL_ERROR "no *.spv file found in ${SPV_DIR}")
    endif ()

    set(arrays "")
    set(entries "")
    foreach (spv_file IN LISTS spv_files)
        # my_shader_vs.spv -> key "my_shader_vs.glsl", array SPV_MY_SHADER_VS
        get_filename_component(name "${spv_file}" NAME_WE)
        string(TOUPPER "SPV_${name}" array_name)
        string(MAKE_C_IDENTIFIER "${array_name}" array_name)

        # SPIR-V is a stream of 32-bit little-endian words: regroup the hex
        # dump 4 bytes at a time, least significant byte first
        file(READ "${spv_file}" hex HEX)
        string(REGEX MATCHALL "(..)(..)(..)(..)" words "${hex}")
        set(literals "")
        foreach (word IN LISTS words)
            string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1," literal "${word}")
            string(APPEND literals "${literal}")
        endforeach ()
        string(REGEX REPLACE "(([^,]+,){8})" "\\1\n        " literals "${literals}")

        string(APPEND arrays "    inline constexpr uint32_t ${array_name}[] = {\n        ${literals}\n    };\n")
        string(APPEND entries "        {\"${name}.glsl\", ${array_name}},\n")
    endforeach ()

    string(CONCAT header_content
        "// Auto-generated by cmake/ArenaiCompileShaders.cmake from arenai_view SPIR-V shaders\n"
        "// Do not edit.\n"
        "\n"
        "#ifndef ARENAI_SHADERS_SPIRV_H\n"
        "#define ARENAI_SHADERS_SPIRV_H\n"
        "\n"
        "#include <cstdint>\n"
        "#include <span>\n"
        "#include <string_view>\n"
        "#include <unordered_map>\n"
        "\n"
        "namespace arenai::view {\n"
        "\n"
        "${arrays}"
        "\n"
        "    inline const std::unordered_map<std::string_view, std::span<const uint32_t>>\n"
        "        EMBEDDED_SPIRV = {\n"
        "${entries}"
        "    };\n"
        "\n"
        "}// namespace arenai::view\n"
        "\n"
        "#endif// ARENAI_SHADERS_SPIRV_H\n"
    )

    file(WRITE "${OUTPUT_FILE}" "${header_content}")
    return()
endif ()

##### configure mode: per-shader build rules #####

# Declares the .glsl -> .spv -> <out_header> build rules for every shader of
# <shaders_dir>. The shader stage comes from the file suffix (_vs/_fs).
# Compilation runs the host glslangValidator: the caller must have done
# find_package(Vulkan REQUIRED COMPONENTS glslangValidator) beforehand.
# Appends the generated header to <sources_var> so the caller adds it to its
# target's sources (which triggers the whole chain).
function(arenai_compile_shaders shaders_dir gen_dir out_header sources_var)
    if (NOT TARGET Vulkan::glslangValidator)
        message(FATAL_ERROR "arenai_compile_shaders() needs Vulkan::glslangValidator: "
                "call find_package(Vulkan REQUIRED COMPONENTS glslangValidator) first")
    endif ()

    file(GLOB shader_files CONFIGURE_DEPENDS "${shaders_dir}/*.glsl")
    list(SORT shader_files)
    if (NOT shader_files)
        message(FATAL_ERROR "no *.glsl file found in ${shaders_dir}")
    endif ()

    set(spv_dir "${gen_dir}/spv")
    # Ninja creates OUTPUT directories itself but Makefiles does not: create it
    # at configure time so glslangValidator can write there under both.
    file(MAKE_DIRECTORY "${spv_dir}")
    set(spv_files "")
    foreach (shader_file IN LISTS shader_files)
        get_filename_component(name "${shader_file}" NAME_WE)
        if (name MATCHES "_vs$")
            set(stage vert)
        elseif (name MATCHES "_fs$")
            set(stage frag)
        else ()
            message(FATAL_ERROR "cannot infer shader stage of ${shader_file}: expected a _vs/_fs suffix")
        endif ()

        set(spv_file "${spv_dir}/${name}.spv")
        add_custom_command(
                OUTPUT "${spv_file}"
                COMMAND Vulkan::glslangValidator -V --target-env vulkan1.2 --quiet
                -S ${stage} -o "${spv_file}" "${shader_file}"
                DEPENDS "${shader_file}"
                COMMENT "Compiling ${name}.glsl to SPIR-V"
        )
        list(APPEND spv_files "${spv_file}")
    endforeach ()

    add_custom_command(
            OUTPUT "${out_header}"
            COMMAND ${CMAKE_COMMAND}
            -DSPV_DIR=${spv_dir}
            -DOUTPUT_FILE=${out_header}
            -P ${CMAKE_CURRENT_FUNCTION_LIST_FILE}
            DEPENDS ${spv_files} "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
            COMMENT "Embedding SPIR-V shaders into ${out_header}"
    )

    list(APPEND ${sources_var} "${out_header}")
    set(${sources_var} "${${sources_var}}" PARENT_SCOPE)
endfunction()
